# Generated by Django 4.2.7 on 2026-03-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("executions", "0003_alter_execution_options_alter_execution_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="execution",
            name="assigned_to",
            field=models.EmailField(
                blank=True,
                help_text="Email of the user currently responsible for this execution",
                max_length=254,
                null=True,
            ),
        ),
    ]
