# Generated by Django 4.2.7 on 2026-03-17 13:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("executions", "0004_execution_assigned_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step_id", models.UUIDField()),
                ("action", models.CharField(max_length=20)),
                ("is_used", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="executions.execution",
                    ),
                ),
            ],
        ),
    ]
