# Generated by Django 4.2.7 on 2026-03-17 14:13

from django.db import migrations, models
import django.db.models.deletion
import uuid

def create_default_roles_and_link_users(apps, schema_editor):
    Company = apps.get_model('authentication', 'Company')
    Role = apps.get_model('authentication', 'Role')
    User = apps.get_model('authentication', 'User')

    for company in Company.objects.all():
        # Create default roles
        admin_role, _ = Role.objects.get_or_create(
            company=company, 
            name='Admin', 
            defaults={'is_admin': True}
        )
        employee_role, _ = Role.objects.get_or_create(
            company=company, 
            name='Employee', 
            defaults={'is_admin': False}
        )
        # We'll treat 'super_admin' as 'Admin' for now, but we can extend this.
        
        # Link existing users
        for user in User.objects.filter(company=company):
            if user.role_old in ['admin', 'super_admin']:
                user.role = admin_role
            else:
                user.role = employee_role
            user.save()

class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_company_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "name")},
            },
        ),
        # Rename existing role to role_old
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='role_old',
        ),
        # Add new role as ForeignKey
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='authentication.role',
            ),
        ),
        # Migrate data
        migrations.RunPython(create_default_roles_and_link_users),
        # Remove role_old
        migrations.RemoveField(
            model_name='user',
            name='role_old',
        ),
    ]
