# Generated by Django 4.2.7 on 2026-03-17 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rule",
            options={"ordering": ["priority"]},
        ),
    ]
